name: Endor Labs Example
on: push
jobs:
  build-and-scan:
    permissions:
      id-token: write   # Write permission is required to request a JWT token to perform keyless authentication
      contents: read  # Required by actions/checkout@v3 to checkout a private repository.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile Package
        run: mvn clean install
      - name: Scan with Endor Labs
        uses: endorlabs/github-action@02231267f2d7d3be21f10662fdd39fba143d4bda # v1.1.9
        with:
          namespace: "example" # Update with your Endor Labs namespace  